#!/usr/bin/env bash

: "${LAKEFS_ENDPOINT:=http://localhost:8000}"
: "${LAKEFS_ACCESS_KEY_ID:=AKIAIOSFOLQUICKSTART}"
: "${LAKEFS_SECRET_ACCESS_KEY:=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}"
: "${LAKEFS_REPOSITORY:=artifact-layer-it}"
: "${LAKEFS_STORAGE_NAMESPACE_PREFIX:=local://}"
: "${LAKEFS_CANONICAL_BRANCH:=main}"

export LAKEFS_ENDPOINT
export LAKEFS_ACCESS_KEY_ID
export LAKEFS_SECRET_ACCESS_KEY
export LAKEFS_REPOSITORY
export LAKEFS_STORAGE_NAMESPACE_PREFIX
export LAKEFS_CANONICAL_BRANCH
